-- Active: 1767363723104@@127.0.0.1@3306@dbms_clg
CREATE DATABASE IF NOT EXISTS DBMS_CLG;
DROP TABLE payment;
CREATE TABLE PAYMENT (
    CUSTOMER_ID INT PRIMARY KEY,
    P_ID INT UNIQUE,
    AMOUNT INT NOT NULL,
    ORDER_ID VARCHAR(50) UNIQUE
);

INSERT INTO PAYMENT 
(CUSTOMER_ID, P_ID, AMOUNT, ORDER_ID)
VALUES
(1, 32, 56000, "abc-sdvs-fdsbn"),
(2, 23, 96000, "bxcv-hgvcbn-fdsbn"),
(3, 12, 12000, "kjhgcv-gdbne-245vb"),
(4, 90, 34000, "rtghd-gvhjbndm-356tge");

SELECT CUSTOMER_ID AS C_ID, P_ID AS PRODUCT_ID, AMOUNT AS AMT,
ORDER_ID AS O_ID, AMOUNT*12 AS ANNUAL_COST  FROM payment;


CREATE TABLE ORDER_PICK(
    P_ID INT,
    ORDER_ID VARCHAR(50),
    FOREIGN KEY (P_ID) REFERENCES PAYMENT(P_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES PAYMENT(ORDER_ID)
);

INSERT INTO ORDER_PICK
(P_ID, ORDER_ID)
VALUES
(32,"abc-sdvs-fdsbn"),
(23,"bxcv-hgvcbn-fdsbn"),
(12,"kjhgcv-gdbne-245vb"),
(90,"rtghd-gvhjbndm-356tge");
SELECT `P_ID`, `ORDER_ID`AS O_ID FROM ORDER_PICK;
