-- Active: 1767363723104@@127.0.0.1@3306@dbms_clg
CREATE DATABASE IF NOT EXISTS DBMS_CLG;

USE DBMS_CLG;

CREATE TABLE EMP (SALARY INT, JOB VARCHAR(25));

INSERT INTO
    EMP (SALARY, JOB)
VALUES (2300000, "SWE EXPERT"),
    (4300000, "MARKETING EXPERT"),
    (1900000, "ANALYST"),
    (210000, "GUIDE"),
    (8900000, "MANAGE");

SELECT * FROM emp;

ALTER TABLE emp ADD COLUMN DEPARTMENT_NO INT;

UPDATE emp SET `DEPARTMENT_NO` = 10 WHERE `JOB` = "SWE EXPERT";

UPDATE emp
SET
    `DEPARTMENT_NO` = 20
WHERE
    `JOB` = "MARKETING EXPERT";

UPDATE emp SET `DEPARTMENT_NO` = 30 WHERE `JOB` = "ANALYST";

UPDATE emp SET `DEPARTMENT_NO` = 40 WHERE `JOB` = "GUIDE";

UPDATE emp SET `DEPARTMENT_NO` = 50 WHERE `JOB` = "MANAGE";

UPDATE DBMS_CLG.EMP SET `DEPARTMENT_NO` = FLOOR(1 + RAND() * 50);

SELECT MAX(SALARY)
AS HIGHEST_SALARY FROM emp;

SELECT MIN(`SALARY`), MAX(`SALARY`), SUM(`SALARY`), AVG(`SALARY`) FROM emp;

SELECT COUNT(*) FROM EMP; 